### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by wesley-dean-flexion** [sclevine/yj#8]
Hi.  I love this tool!  Thank you very much for putting it together!!

I use Docker for many (most?) of my work and it's very handy for me to be able to use containerized builds of tools that I frequently use.  Seeing as how yj didn't have a Dockerfile to build an image, I put one together and submitted it as a PR (#7).

If you're open to it, it would be super-swell if the image could be made available on dockerhub.  Assuming the PR is accepted, dockerhub could be set to automatically build the image when a commit to the yj repo on github is pushed.

Also, if you want, I can document the build / run process in the README.md file.

Thanks again!!

**Comment by sclevine** [comment]
Thanks for the contribution, and sorry for the delay. I merged #7, but then I switched the base image to [scratch](https://github.com/sclevine/yj/blob/master/Dockerfile) so that the final image is much smaller.

I went ahead and pushed v4.0.0 to [Docker Hub](https://hub.docker.com/r/sclevine/yj/tags), and I'll consider switching to an automated build for the next release.
